In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("Housepriceprediction.csv")

In [3]:
df.head()

Id  LotArea  OverallQual  1stFlrSF  GrLivArea  TotRmsAbvGrd  GarageCars  \
0   1     8450            7       856       1710             8           2   
1   2     9600            6      1262       1262             6           2   
2   3    11250            7       920       1786             6           2   
3   4     9550            7       961       1717             7           3   
4   5    14260            8      1145       2198             9           3   

   GarageArea  SalePrice  
0         548     208500  
1         460     181500  
2         608     223500  
3         642     140000  
4         836     250000

In [4]:
df.shape

(1460, 9)

In [5]:
#Find how many null values are there in feature column
df.isnull().sum()

Id              0
LotArea         0
OverallQual     0
1stFlrSF        0
GrLivArea       0
TotRmsAbvGrd    0
GarageCars      0
GarageArea      0
SalePrice       0
dtype: int64

In [6]:
#Now we are going to drop column Id asit is of no use
df=df.drop(['Id'],axis=1)
print(df.head())
print(df.shape)

   LotArea  OverallQual  1stFlrSF  GrLivArea  TotRmsAbvGrd  GarageCars  \
0     8450            7       856       1710             8           2   
1     9600            6      1262       1262             6           2   
2    11250            7       920       1786             6           2   
3     9550            7       961       1717             7           3   
4    14260            8      1145       2198             9           3   

   GarageArea  SalePrice  
0         548     208500  
1         460     181500  
2         608     223500  
3         642     140000  
4         836     250000  
(1460, 8)


In [7]:
df['LotArea'].head()

0     8450
1     9600
2    11250
3     9550
4    14260
Name: LotArea, dtype: int64

In [8]:
#Imp. syntax
(df['LotArea']-1).head()

0     8449
1     9599
2    11249
3     9549
4    14259
Name: LotArea, dtype: int64

In [9]:
df['LotArea'].max()


215245

In [10]:
df.columns

Index(['LotArea', 'OverallQual', '1stFlrSF', 'GrLivArea', 'TotRmsAbvGrd',
       'GarageCars', 'GarageArea', 'SalePrice'],
      dtype='object')

In [11]:
for i in df.columns:
    print(df[i].head())

0     8450
1     9600
2    11250
3     9550
4    14260
Name: LotArea, dtype: int64
0    7
1    6
2    7
3    7
4    8
Name: OverallQual, dtype: int64
0     856
1    1262
2     920
3     961
4    1145
Name: 1stFlrSF, dtype: int64
0    1710
1    1262
2    1786
3    1717
4    2198
Name: GrLivArea, dtype: int64
0    8
1    6
2    6
3    7
4    9
Name: TotRmsAbvGrd, dtype: int64
0    2
1    2
2    2
3    3
4    3
Name: GarageCars, dtype: int64
0    548
1    460
2    608
3    642
4    836
Name: GarageArea, dtype: int64
0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64


### Normalization
1.Normalization is conducted to make features value ranges from 0 to 1.
          x=[x-min(x)/{max(x)-min(x)}]<br>
2.This whole process is also know as MinMaxScaler

In [12]:
#1st method:-
#By calculating through formula
def normalize(f5):
    result=f5.copy()
    for i in df.columns:
        max_value=df[i].max()
        min_value=df[i].min()
        result[i]=(df[i]-min_value)/(max_value-min_value)
    return result
    

In [13]:
df1=normalize(df)
df1

LotArea  OverallQual  1stFlrSF  GrLivArea  TotRmsAbvGrd  GarageCars  \
0     0.033420     0.666667  0.119780   0.259231      0.500000        0.50   
1     0.038795     0.555556  0.212942   0.174830      0.333333        0.50   
2     0.046507     0.666667  0.134465   0.273549      0.333333        0.50   
3     0.038561     0.666667  0.143873   0.260550      0.416667        0.75   
4     0.060576     0.777778  0.186095   0.351168      0.583333        0.75   
...        ...          ...       ...        ...           ...         ...   
1455  0.030929     0.555556  0.142038   0.247362      0.416667        0.50   
1456  0.055505     0.555556  0.399036   0.327619      0.416667        0.50   
1457  0.036187     0.666667  0.195961   0.377920      0.583333        0.25   
1458  0.039342     0.444444  0.170721   0.140166      0.250000        0.25   
1459  0.040370     0.444444  0.211565   0.173700      0.333333        0.25   

      GarageArea  SalePrice  
0       0.386460   0.241078  
1       0.324401   0.203583  
2       0.428773   0.261908  
3       0.452750   0.145952  
4       0.589563   0.298709  
...          ...        ...  
1455    0.324401   0.194556  
1456    0.352609   0.243161  
1457    0.177715   0.321622  
1458    0.169252   0.148903  
1459    0.194640   0.156367  

[1460 rows x 8 columns]

In [14]:
#2nd method:
#By using the library of python
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df2=scaler.fit_transform(df)

In [15]:
#We need to convert array format to dataframe format
df2

array([[0.0334198 , 0.66666667, 0.11977972, ..., 0.5       , 0.3864598 ,
        0.24107763],
       [0.03879502, 0.55555556, 0.21294172, ..., 0.5       , 0.32440056,
        0.20358284],
       [0.04650728, 0.66666667, 0.13446535, ..., 0.5       , 0.42877292,
        0.26190807],
       ...,
       [0.03618687, 0.66666667, 0.19596145, ..., 0.25      , 0.17771509,
        0.321622  ],
       [0.03934189, 0.44444444, 0.17072051, ..., 0.25      , 0.16925247,
        0.14890293],
       [0.04037019, 0.44444444, 0.21156494, ..., 0.25      , 0.19464034,
        0.15636717]])

In [16]:
df2=pd.DataFrame(df2,columns=['LotAera','OverallQual', '1stFlrSF', 'GrLivArea', 'TotRmsAbvGrd',
       'GarageCars', 'GarageArea', 'SalePrice'])

In [17]:
df2

LotAera  OverallQual  1stFlrSF  GrLivArea  TotRmsAbvGrd  GarageCars  \
0     0.033420     0.666667  0.119780   0.259231      0.500000        0.50   
1     0.038795     0.555556  0.212942   0.174830      0.333333        0.50   
2     0.046507     0.666667  0.134465   0.273549      0.333333        0.50   
3     0.038561     0.666667  0.143873   0.260550      0.416667        0.75   
4     0.060576     0.777778  0.186095   0.351168      0.583333        0.75   
...        ...          ...       ...        ...           ...         ...   
1455  0.030929     0.555556  0.142038   0.247362      0.416667        0.50   
1456  0.055505     0.555556  0.399036   0.327619      0.416667        0.50   
1457  0.036187     0.666667  0.195961   0.377920      0.583333        0.25   
1458  0.039342     0.444444  0.170721   0.140166      0.250000        0.25   
1459  0.040370     0.444444  0.211565   0.173700      0.333333        0.25   

      GarageArea  SalePrice  
0       0.386460   0.241078  
1       0.324401   0.203583  
2       0.428773   0.261908  
3       0.452750   0.145952  
4       0.589563   0.298709  
...          ...        ...  
1455    0.324401   0.194556  
1456    0.352609   0.243161  
1457    0.177715   0.321622  
1458    0.169252   0.148903  
1459    0.194640   0.156367  

[1460 rows x 8 columns]

In [18]:
#Both df1 and df2 is same...

In [19]:
y=df2['SalePrice'].values
x=df2.drop(['SalePrice'],axis=1)
print(y.shape)


(1460,)


In [20]:
x.shape

(1460, 7)

In [21]:
X_train=x[:1000]
Y_train=y[:1000]
X_test=x[1000:]
Y_test=y[1000:]
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(1000, 7) (1000,)
(460, 7) (460,)


# Sklearn LinearRegression

In [22]:
from sklearn.linear_model import LinearRegression
linear_regression = LinearRegression()
linear_regression.fit(X_train,Y_train )


LinearRegression()

In [23]:
linear_regression.predict(X_test)

array([ 0.05256727,  0.06611535,  0.32796352,  0.20671707,  0.24678915,
        0.10902359,  0.23708032,  0.04953625,  0.28300887,  0.1122695 ,
        0.12308401,  0.1569166 ,  0.16310674,  0.10771183,  0.15161809,
        0.26628149,  0.2551894 ,  0.27505085,  0.21290885,  0.24519149,
        0.10119321,  0.23110982,  0.11026336,  0.24543575,  0.4592156 ,
        0.11125299,  0.15436659,  0.33200852,  0.12596005,  0.13324869,
        0.13543142,  0.37587591,  0.37394678,  0.30214384,  0.09741419,
        0.05773704,  0.37495069,  0.34003708,  0.0513334 ,  0.02459742,
        0.2184113 ,  0.19048027,  0.20181013,  0.30911548,  0.40493869,
        0.13762001,  0.45817389,  0.13851567,  0.21289195,  0.06829938,
        0.22806158,  0.23172282,  0.23195539,  0.17050331,  0.30610527,
        0.22153166,  0.23632718,  0.26463765,  0.37904776,  0.22441845,
        0.2740921 ,  0.1090954 ,  0.23720076,  0.16798855,  0.14524807,
        0.29547298,  0.17872478,  0.1868581 ,  0.26997531,  0.12

In [24]:
Y_test

array([0.06540758, 0.07096237, 0.27371198, 0.14165394, 0.20288849,
       0.15970004, 0.17858631, 0.07373976, 0.28482155, 0.0931815 ,
       0.13900847, 0.09040411, 0.18066935, 0.06957367, 0.11706707,
       0.2667685 , 0.2334398 , 0.21191501, 0.17372587, 0.24800722,
       0.19594501, 0.22094154, 0.07235106, 0.21677545, 0.35009027,
       0.10776281, 0.18414109, 0.35852937, 0.09734759, 0.11540064,
       0.17372587, 0.22510762, 0.38203027, 0.27093459, 0.11783086,
       0.06818497, 0.3896681 , 0.35009027, 0.08623802, 0.06263019,
       0.16678239, 0.19177892, 0.22371893, 0.3157617 , 0.337592  ,
       0.14539647, 0.72445633, 0.15289543, 0.11123455, 0.0694348 ,
       0.19661853, 0.22946952, 0.18066935, 0.15220108, 0.30565199,
       0.20149979, 0.20962366, 0.29593112, 0.41674767, 0.25704763,
       0.24802111, 0.06401889, 0.07651715, 0.10498542, 0.1653937 ,
       0.4070268 , 0.1987224 , 0.18469657, 0.16178309, 0.13900847,
       0.13900847, 0.1653937 , 0.07860019, 0.17303152, 0.22094

In [27]:
#Accracy of model
linear_regression.score(X_test,Y_test)

0.6825983265973221

In [30]:
#k fold cross validation
import numpy as np
from sklearn.model_selection import KFold
linear_regression
kflod_validation=KFold(10)


In [34]:
from sklearn.model_selection import cross_val_score as sc
results=sc(linear_regression,x,y,cv=kflod_validation)
print(results)
print(np.mean(results))

[0.76666015 0.82979843 0.86081925 0.70110168 0.76949442 0.76945646
 0.74996655 0.75073452 0.58088786 0.80069797]
0.7579617282926168


In [35]:
#Leave one our cross validation(LOOCV)